"""Project repld bootstrap — executed by the kernel at boot, before any cell.

Generated by /devstack:project-init. Owned by this project from here on:
edit freely, it is not overwritten by plugin updates.
"""

from pathlib import Path

# repld.gists, not a bare `import gists` -- that resolves to the project's
# own ./gists directory as an empty namespace package, not this API.
from repld import gists

# The devstack GIT CHECKOUT, not the plugin cache under ~/.claude/plugins/
# (that path embeds the plugin version and changes on every update, which
# would silently strand this kernel on a stale copy). The checkout is
# stable and tracks whatever is pulled.
#
# Precedence: ~/.repld/gists and this project's ./gists both beat this dir,
# so a ./gists/<name>.py shadows a plugin gist by name. ./gists here holds
# Fredrik's own automation gists (finn, tiktok, shopify, ...) — none of
# them collide with the devstack names. A shadow file CREATED after this
# kernel booted is not live until kernel restart -- `gists.resolve(name)`
# names the new winner while the imported module's `__file__` keeps the
# old one; that disagreement is the diagnostic.
gists.add_search_dir(
    Path(
        "~/Projects/private/devstack/plugins/devstack/skills/dispatch-loop/gists"
    ).expanduser()
)

# devloop's live-drive gists (DevServer, android.Device, ios.IOSDevice,
# DevBridge). Not wired: repld's own browser tests already drive real
# Chrome directly via CDP (tests/phases/browser.py) — a separate,
# already-established live-verification path. Uncomment if that changes.
# gists.add_search_dir(Path("~/Projects/private/devstack/plugins/devloop/skills/dev-loop/gists").expanduser())
